name: Deploy ASP.NET Merge Application to Azure App Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  AZURE_WEBAPP_NAME: Merge-app-service-slotmachineapplication
    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.\code\Merge\'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@main
        
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet restore
      - name: dotnet restore
        run: dotnet restore .\code\Merge\Merge.csproj
          
        # Run dotnet build
      - name: dotnet build
        run:  dotnet build --configuration Release .\code\Merge\Merge.csproj
          
        # Run dotnet publish
      - name: dotnet publish
        run:  dotnet publish -c Release .\code\Merge\Merge.csproj
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.MERGE_APP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
