name: Deploy ASP.NET Numbers Application to Azure App Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
env:
  AZURE_WEBAPP_NAME: Number-app-service-slotmachineapplication   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './code/BonusNumber'      # set this to the path to your web app project, defaults to the repository root
  NUGET_VERSION: '5.8.0'           # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@main  
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore .\code\BonusNumber\BonusNumber.csproj
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run MSBuild
      run: msbuild .\code\BonusNumber\BonusNumber.csproj
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.NUMBER_APP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/'
